from nnUtils import *

model = Sequential([
    SpatialConvolution(128,3,3,1,1, padding='VALID', bias=False),
    BatchNormalization(name='L2_Batch'),
    ReLU(),
    SpatialConvolution(128,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2,name='L5_MaxPooling'),
    BatchNormalization(name='L6_Batch'),
    ReLU(),
    SpatialConvolution(256,3,3, padding='SAME', bias=False),
    BatchNormalization(name='L9_Batch'),
    ReLU(),
    SpatialConvolution(256,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2,name='L12_MaxPooling'),
    BatchNormalization(name='L13_Batch'),
    ReLU(),
    SpatialConvolution(512,3,3, padding='SAME', bias=False),
    BatchNormalization(name='L16_Batch'),
    ReLU(),
    SpatialConvolution(512,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2,name='L19_MaxPooling'),
    BatchNormalization(name='L20_Batch'),
    ReLU(),
    Affine(1024, bias=False),
    BatchNormalization(name='L23_Batch'),
    ReLU(),
    Affine(1024, bias=False),
    BatchNormalization(name='L26_Batch'),
    ReLU(),
    Affine(10, bias=False)
])
